// Generated by Selenium IDE
using System;
using System.Diagnostics.Contracts;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using NUnit.Framework;

namespace WebAddressbookTests
{
    [TestFixture]
    public class Task5_ContactCreationTest :Task5_TestBase
    {
        [Test]
        public void ContactCreationTest()
        {
            OpenHomePage();
            Login(new AccountData("admin", "secret"));
            AddNewContact();
            ContactData contacts = new ContactData("marta", "johnson", "Los Angeles, California", "martaj@gmail.com");
            //contacts.MiddleName = "";
            //contacts.NickName = "";
            //contacts.Title = "";
            //contacts.Company = "";
            //contacts.Home = "";
            //contacts.Mobile = "";
            //contacts.Work = "";
            //contacts.Fax = "";
            //contacts.Email2 = "";
            //contacts.Email3 = "";
            //contacts.Homepage = "";
            //contacts.Address2 = "";
            //contacts.Phone2 = "";
            //contacts.Notes = "";
            FillContactData(contacts);
            SubmitNewContact();
            Logout();
        }  

    }
}

